version: "3.8"
services:
  magento_news_bot:
    build: ./
    working_dir: /bot
    command:
      - /bot/bin/bot
    volumes:
      - ./:/bot
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DB}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - /lib/postgres_com:/data/db
